### ISSUE TITLE
Power command issues

### ISSUE THREAD

**Issue by Erokani** [TroX-oO/homebridge-freemote#1]
Hi,

First, a big thanks for your plugin! I’m running it every day via some automation rules to power it up & down and via the voice to select channels :)

Among the time I spotted 2 issues that you may be in position to fix:
- You need sometimes several tries to make the power up/down command effective. I don’t know if related to freebox player deep sleep or not. Let me know what you would need from me to investigate. 
- when powered down from the replay, then powering it up via the plugin bring you to the replay home screen, with TV channel selection via the plugin ineffective until taking the remote and pressing menu. Could you fix this use case?

Thank you in advance
Kind regards,
Mat

Note: I have an HomePod as HomeKit Hub, and homebridge running on a Synology NAS.

**Comment by TroX-oO** [comment]
Hi, i'm glad that you enjoy this plugin :)

Unfortunately, I don't have a Freebox anymore so I'm not using it since almost a year.
Indeed, there are some power issues cause the Freebox API does not provide a way to know if the Player is powered on or not. There is a trick using wether or not a AirMedia is currently playing or not. (If yes, the player is On, otherwise it's Off). But it is quite buggy.

That is why the power command is weird under certain conditions.
I don't know if Free does something to change this behaviour but, at the moment, I didn't find better ways to do it.

For your first problem, if it's need several tries, it is because it didn't get response whether or not the Freebox Player is currently On.

For your second, the plugin is a little "silly". The power command is literally "Press power button, then press Ok after 5 seconds".

I supposed that the freebox would power on into the main menu, not the replay screen.
Once again, I don't know if the API provide a way to know in which menu the freebox is. (I don't think there is) 
So maybe, a trick would be to press the home button in between to be sure that the Freebox is on the main menu.

If you wish to do so, try replacing in FreemoteApi.js line 150

```
          .then(function() {
            setTimeout(self.remote.bind(self, 'ok'), 5000);
          });
```

by

```
          .then(function() {
            setTimeout(self.remote.bind(self, 'home'), 5000);
            setTimeout(self.remote.bind(self, 'ok'), 8000);
          });
```

as a consequence, your startup time will be a little bit longer (you can try different value to adjust and get the minimum possible)

I hope this helps.
